version: '3.8'

services:
  server:
    build: ./server
    container_name: my-java-server
    restart: on-failure
    command: ["java", "-jar", "server-1.0-SNAPSHOT.jar", "output.json"]

  client:
    build: ./client
    depends_on:
      server:
        condition: service_started
    environment:
      SERVER_HOST: server
      SERVER_PORT: 12345
    volumes:
      - ./sdf.txt:/app/sdf.txt
    stdin_open: true
    tty: true
